name: Step 2, Assessment

on:
  push:
    branches:
      - add-world

permissions: write-all

jobs:
  check-solution:
    name: Checking User Submission...
    runs-on: ubuntu-latest
    outputs:
      assessment: ${{ steps.check.outputs.assessment }}
      reason: ${{ steps.check.outputs.reason }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Solution
        id: check
        uses: andrewdmaclean-work/learn-action-check-file@main
        with:
          step: ".github/steps/2-add-world.md"
          submission: "hello-world.md"
          solution: ".github/solutions/2-solution-prompt.md"
  handle-results:
    name: Leaving Comments for User...
    runs-on: ubuntu-latest
    needs: check-solution
    steps:
      - name: Handle Solution Result
        uses: andrewdmaclean-work/learn-action-ai-assistant-comments@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          assessment: ${{ needs.check-solution.outputs.assessment }}
          reason: ${{ needs.check-solution.outputs.reason }}
  evaluate-assessment:
    name: Checking if Ready to Progress...
    runs-on: ubuntu-latest
    needs: check-solution
    steps:
      - name: Check Assessment
        if: needs.check-solution.outputs.assessment == 'correct'
        run: echo "Your submission is correct. Continue to the next step."

      - name: Fail Assessment
        if: needs.check-solution.outputs.assessment != 'correct'
        run: |
          echo "Your submission is missing something. Please review the comments."
          exit 1
  update-step:
    name: Updating Instructions...
    runs-on: ubuntu-latest
    needs: evaluate-assessment
    if: needs.check-solution.outputs.assessment == 'correct'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Merge current PR
        run: |

          echo "Checking current step..."
          if [ "$(cat .github/steps/-step.txt)" != 1 ]
          then
            echo "Current step is not 1"
            exit 0
          fi

          echo "Authenticating gh CLI..."
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          if [ -z "${{ github.event.pull_request.number }}" ]; then
            echo "No PR context: skipping merge."
          else
            echo "Merging PR #${{ github.event.pull_request.number }}..."
            gh pr merge ${{ github.event.pull_request.number }} --merge --admin --delete-branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure we are on Step 2
        run: |
          echo "Make sure we are on step 2"
          if [ "$(cat .github/steps/-step.txt)" != 2 ]
          then
            echo "Current step is not 2"
            exit 0
          fi
      - name: Update to step X
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: X
          branch_name: main
