name: Step X, Completion

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  finish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read current step
        id: get_step
        run: |
          current_step=$(cat .github/steps/-step.txt)
          echo "current_step=$current_step" >> $GITHUB_OUTPUT

      - name: Exit unless step X
        if: steps.get_step.outputs.current_step != 'X'
        run: |
          echo "Current step is not X (found ${steps.get_step.outputs.current_step}), exiting."
          exit 0

      - name: Update README for Step X Completion
        if: steps.get_step.outputs.current_step == 'X'
        run: |
          NAME="${{ github.actor }}"
          sed -i "s/X-NAME/$NAME/g" README.md
          # Put your X-MESSAGE update here if desired (or just hardcode it)
          sed -i "s/X-MESSAGE/Congratulations on finishing step X!/g" README.md

      - name: Commit changes
        if: steps.get_step.outputs.current_step == 'X'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README to celebrate Step X"
          git push